# fly.toml app configuration file generated for fast-sign on 2023-07-11T14:07:55+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fast-sign"
primary_region = "hkg"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
