name: CI CD
on:
  push:
    # branches:
    #   - main
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout this repo
        uses: actions/checkout@v3

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'pnpm'

      - name: install dependencies
        run: pnpm install

      - name: run tests
        id: run-tests
        run: pnpm test

      - name: Upload test report
        if: failure() && steps.run-tests.outcome == 'failure'
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: test.json
